### ISSUE TITLE
InvalidUriChar in query string parameters

### ISSUE THREAD

**Issue by ecejeff** [awslabs/aws-lambda-rust-runtime#461] opened 2022-04-05 15:11 UTC
Hi,

I'm just getting started with using rust with AWS Lambda and set up a test that I could see how the API gateway transformed various inputs.

Here's my test rust lambda file:
```use lambda_http::{service_fn, Error, IntoResponse, Request, RequestExt};

#[tokio::main]
async fn main() -> Result<(), Error> {
    lambda_http::run(service_fn(func)).await?;
    Ok(())
}

async fn func(event: Request) -> Result<impl IntoResponse, Error> {
    let query = event.query_string_parameters();
    let path = event.path_parameters();
    let stage = event.stage_variables();

    let res = format!("The raw path for this request is: \nevent={event:#?}\nstage={stage:#?}\npath={path:#?}\nquery={query:#?}").into_response();

    Ok(res)
}
```

Cargo.toml:
```
[dependencies]
lambda_runtime = "0.5.1"
lambda_http = "0.5.1"
log = "0.4.14"
serde_json = "1.0.79"
simple_logger = "2.1.0"
tokio = {version = "1.17.0", features = ["full"]}
```

When accessing through a URL with spaces in the parameters such as `https://myapiendpoint.execute-api.us-east-1.amazonaws.com/prod?param1=test%20with%20spaces` I get the following error:

```
START RequestId: cd9b44d3-7a0c-4965-9073-d76bbd408769 Version: $LATEST
--
thread 'main' panicked at 'failed to build request: http::Error(InvalidUri(InvalidUriChar))', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/lambda_http-0.5.1/src/request.rs:170:10
stack backtrace:
0: rust_begin_unwind
at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
1: core::panicking::panic_fmt
at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
2: core::result::unwrap_failed
at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
3: lambda_http::request::into_proxy_request
4: lambda_http::request::<impl core::convert::From<lambda_http::request::LambdaRequest> for http::request::Request<aws_lambda_events::encodings::Body>>::from
5: <lambda_http::Adapter<R,S> as tower_service::Service<lambda_runtime::types::LambdaEvent<lambda_http::request::LambdaRequest>>>::call
6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
7: std::thread::local::LocalKey<T>::with
8: tokio::park::thread::CachedParkThread::block_on
9: tokio::runtime::Runtime::block_on
10: serial_number::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
END RequestId: cd9b44d3-7a0c-4965-9073-d76bbd408769
REPORT RequestId: cd9b44d3-7a0c-4965-9073-d76bbd408769	Duration: 484.61 ms	Billed Duration: 503 ms	Memory Size: 128 MB	Max Memory Used: 19 MB	Init Duration: 17.89 ms
```

Everything works as expected when there are no spaces in the parameters. Is this a bug, or am I doing something wrong?

**Comment by calavera** [comment] 2022-04-05 15:29
That looks like a bug to me

**Comment by calavera** [comment] 2022-05-05 17:04
I believe this is fixed in the latest release of lambda-http. Let me know if it's still a problem, and I'll reopen the issue.

**Closed by calavera** 2022-05-05 17:04 UTC

**Comment by ecejeff** [comment] 2022-05-06 14:06
Looks good. Thanks!

**Comment by qstorey** [comment] 2022-08-20 20:27
Hi, is it possible this bug still exists?

I upgraded to lambda_http 0.6.0 but I get the same error when a URL includes spaces.
```
thread 'main' panicked at 'failed to build request: http::Error(InvalidUri(InvalidUriChar))', /cargo/registry/src/github.com-1ecc6299db9ec823/lambda_http-0.6.0/src/request.rs:145:10
```

I you would like I can create a repo to reproduce this.

**Comment by qstorey** [comment] 2022-08-22 06:58
@calavera sure thing. I will open a new issue and include all the details to reproduce it.
