### ISSUE TITLE
/lib64/libc.so.6: version `GLIBC_2.18' not found

### ISSUE THREAD

**Issue by Dgame** [awslabs/aws-lambda-rust-runtime#17] opened 2018-11-30 14:47 UTC
I'm building the lambda on Ubuntu with the basic example you've provided in the README.
It builds without any errors but if I upload and test it on aws in crashes with:

```
{
  "errorType": "Runtime.ExitError",
  "errorMessage": "RequestId: c24d34ab-f4a9-11e8-a9b7-d5cbfb363674 Error: Runtime exited with error: exit status 1"
}
```

The log output is:

```
START RequestId: c24d34ab-f4a9-11e8-a9b7-d5cbfb363674 Version: $LATEST
/var/task/bootstrap: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /var/task/bootstrap)
END RequestId: c24d34ab-f4a9-11e8-a9b7-d5cbfb363674
REPORT RequestId: c24d34ab-f4a9-11e8-a9b7-d5cbfb363674	Duration: 61.35 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 12 MB	
RequestId: c24d34ab-f4a9-11e8-a9b7-d5cbfb363674 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by davidbarsky** [comment] 2018-11-30 18:46
Oh man, I'm not sure, and I don't have an Ubuntu instance handy. Can you try building this using musl-libc instead of GNU libc? This would entail adding the `x86_64-unknown-linux-musl` target using `rustup`.

**Comment by sapessi** [comment] 2018-12-01 17:55
@Dgame I would probably use a [docker image](https://hub.docker.com/r/library/amazonlinux/tags/) to build in local. AWS Lambda uses [Amazon Linux 2017.03.1](https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html). We are working to add [Rust support to SAM build](https://github.com/awslabs/aws-lambda-builders/pull/43).

**Comment by drogus** [comment] 2018-12-02 23:08
I get the same error when compiling on Arch Linux. And it seems that using amazonlinux doesn't help, building with a docker image yields the same result. Here's a Dockerfile that I used: https://gist.github.com/drogus/e16260baa0210a30922a3808a9eed8ff

After building it I just ran the command from the README:

```
cargo build -p lambda_runtime --example basic --release 
```

**Comment by drogus** [comment] 2018-12-02 23:45
That said, building with musl works correctly (on Arch I installed the musl package and added a `x86_64-unknown-linux-musl` target)

**Comment by sapessi** [comment] 2018-12-03 00:42
Mh, I was able to cargo build successfully and run the basic example with this Dockerfile:

```dockerfile
FROM amazonlinux:2017.03.1.20170812
RUN curl https://sh.rustup.rs -sSf | /bin/sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN rustup install stable
RUN yum install -y gcc gcc-c++ make openssl openssl-devel
RUN mkdir /code
WORKDIR /code
```

I will try to replicate with Nightly next, not sure what's causing your issue yet.

**Comment by Dgame** [comment] 2018-12-03 07:40
>@Dgame I would probably use a docker image to build in local. AWS Lambda uses Amazon Linux 2017.03.1. We are working to add Rust support to SAM build.

Well, we are already doing that, but there was the slight hope that building it locally would be faster.

>Oh man, I'm not sure, and I don't have an Ubuntu instance handy. Can you try building this using musl-libc instead of GNU libc? This would entail adding the x86_64-unknown-linux-musl target using rustup.

I've tried but I get this:

>rustup install stable-musl
info: syncing channel updates for 'stable-x86_64-unknown-linux-musl'
info: latest update on 2018-11-08, rust version 1.30.1 (1433507eb 2018-11-07)
error: target not found: 'x86_64-unknown-linux-musl'

**Comment by Dgame** [comment] 2018-12-03 15:02
I've tried
>cargo build --release --target=x86_64-unknown-linux-musl

but then I get those strange OpenSSL errors which I don't get if I drop `--target=x86_64-unknown-linux-musl`:
>Compiling openssl-sys v0.9.39
error: failed to run custom build command for `openssl-sys v0.9.39`
process didn't exit successfully: `/mnt/lambda/target/release/build/openssl-sys-a16ee2b07ae0e6c5/build-script-main` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_DIR
cargo:rerun-if-env-changed=OPENSSL_DIR
run pkg_config fail: "Cross compilation detected. Use PKG_CONFIG_ALLOW_CROSS=1 to override"

>--- stderr
thread 'main' panicked at '

>Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.

>Make sure you also have the development packages of openssl installed.
For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

>If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.

>    $HOST = x86_64-unknown-linux-gnu
    $TARGET = x86_64-unknown-linux-musl
    openssl-sys = 0.9.39

>', /home/dgame/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.39/build/main.rs:269:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

>warning: build failed, waiting for other jobs to finish...
error: build failed

Any ideas?

**Comment by drogus** [comment] 2018-12-03 17:06
@Dgame I'm on ARCH so I'm not sure if it helps you in any way, but I had to specify openssl paths and allow cross compilation:

```
OPENSSL_LIB_DIR=/usr/lib/openssl-1.0
OPENSSL_INCLUDE_DIR=/usr/include/openssl-1.0
PKG_CONFIG_ALLOW_CROSS=1
```

**Comment by Dgame** [comment] 2018-12-04 14:06
@sapessi
I'm using Ubuntu 18.04 and only get those pesky ssl errors if I append `--target=x86_64-unknown-linux-musl`. Without it, it compiles fine but will crash with the error message you can see in my initial post.

@drogus
Thanks, I'll try that next. :)

**Comment by sapessi** [comment] 2018-12-04 16:38
On thing I should have added @Dgame, is that if you use the Amazon Linux Docker container to build then you don't have to specify a `--target` option in the build command.

**Comment by dbcfd** [comment] 2018-12-05 22:10
Until some of the command line tools finish, you may want to use the docker and cargo_config from https://github.com/srijs/rust-aws-lambda/tree/master/docker

More information on setting up environment here: https://github.com/srijs/rust-aws-lambda/blob/master/docs/getting-started.md#Deploy

**Comment by marcomagdy** [comment] 2018-12-05 22:14
@Dgame you could also try using the [C++ runtime](https://github.com/awslabs/aws-lambda-cpp). It deals with this issue seamlessly ;) you can build on Ubuntu, ArchLinux, Alpine, etc.

**Comment by Dgame** [comment] 2018-12-06 08:42
@marcomagdy No, thanks. ;) I've already written the code in rust. It's just about the build time. With Docker it takes ~15 min, without <4min.

**Comment by c-edw** [comment] 2018-12-07 12:54
This is quite painful. I've spent a good few hours trying to get all of the required musl tools and musl Rust target to compile, and now I'm having issues getting openssl-sys to compile on musl. I'd rather not build inside Docker if possible.
@sapessi You mentioned SAM build - will that resolve these difficulties? Thanks.

**Comment by softprops** [comment] 2018-12-11 12:54
You don't actually have to wait for SAM.

If you are a [serverless framework](https://serverless.com/framework/) user you may want to check out the [rust plugin](https://github.com/softprops/serverless-rust) It provides a more seemless build experience as it uses the lambdaci project's "provided" build env ( a faithful replication of the same env you will be deploying into ). 

If you aren't a SAM user you can also just use the a replicated build env, the lambdaci project provides this for custom runtimes. Here's a published extension of that with the rust toolchain pre-installed https://github.com/softprops/lambda-rust#-usage

**Comment by sapessi** [comment] 2018-12-13 18:18
@c-edw SAM build will automatically use docker to build the app. If you'd rather not use docker at all, your alternatives are:

1. Use an amazon linux EC2 instance (with the same AMI as Lambda)
2. Use homebrew to install the required openssl libs - few good pointers in [this issue](https://github.com/sfackler/rust-openssl/issues/255)

**Comment by saethlin** [comment] 2019-01-10 18:39
From my experience, `--target=x86_64-unknown-linux-musl` is only half the battle because openssl is a bit of a bugger to configure and link. To handle that, you can add this to your Cargo.toml dependencies:
```
openssl = { version = "0.10", features = ["vendored"] }
```
The feature will download and compile openssl in your project's `target/` directory, with settings appropriate to the target you're building for. The only possible complication is that you may need to also use the `openssl-probe` crate and call `openssl_probe::init_ssl_cert_env_vars();` immediately in your `main`. Maybe this should be suggested in this project's README?

**Comment by sapessi** [comment] 2019-01-10 19:48
Using the vendored SSL is the easiest way to build this. I'm working with the SAM CLI folks to have a `sam build` command that will work for rust functions and build the project in a container automatically.

**Comment by darrell-roberts** [comment] 2019-01-11 19:46
I had all the same issues. I was building on a mac. I went the docker build route after running into OpenSSL linking issues.

I had to use the [lambci/lambda:build-provided](https://github.com/lambci/docker-lambda) image instead. The image mentioned [here](https://github.com/awslabs/aws-lambda-rust-runtime/issues/17#issuecomment-443558236) resulted in SSL errors when I ran the lambda function in AWS.
```
/var/task/bootstrap: /lib64/libcrypto.so.10: version `OPENSSL_1.0.2' not found (required by /var/task/bootstrap)
```
Here is my Dockerfile

```Dockerfile
FROM lambci/lambda:build-provided
RUN curl https://sh.rustup.rs -sSf | /bin/sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN rustup install stable
# RUN yum install -y gcc gcc-c++ make openssl openssl-devel
RUN mkdir /code
WORKDIR /code
```
Then I ran 
```
docker build . -t lambda_builder

docker run --rm -v ${PWD}:/code -v ${HOME}/.cargo/registry:/root/.cargo/registry -v ${HOME}/.cargo/git:/root/.cargo/git lambda_builder cargo build --release
zip -j lambda.zip target/release/bootstrap
```

**Comment by davidbarsky** [comment] 2019-01-13 23:10
Since most of my day-to-day work is on a Mac, I've used [Cross](https://github.com/rust-embedded/cross) (which recently merged support for macOS!) to build the Lambda function.  

```bash
$ cargo install --force --git https://github.com/rust-embedded/cross # this pulls from master, only needed once
$ cross build --release --target x86_64-unknown-linux-musl
```

**Note**: Cross has a Docker dependency. I've been using Docker Desktop for Mac pretty happily.

**Comment by demerzel3** [comment] 2019-07-23 21:19
> Since most of my day-to-day work is on a Mac, I've used Cross (which recently merged support for macOS!) to build the Lambda function.

Saved my day! Cross should be mentioned in the README, worked flawlessly.

**Comment by konstantinvlasenko** [comment] 2020-01-23 01:47
Hi everyone,

Having the same issue.

- My build environment is AWS EC2 instance (Amazon Linux 2 AMI 2.0.20190313 x86_64 HVM ebs).

- Lambda fails (after successful deployment)  with the same error **/var/task/bootstrap: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /var/task/bootstrap)**

**Comment by davidbarsky** [comment] 2020-01-23 03:38
I think the takeaway of this issue is that this project _has_ to built against musl, as the glibc on the Lambda sandbox is too old for Rust.

**Comment by konstantinvlasenko** [comment] 2020-01-23 15:24
@davidbarsky sorry for my ignorance. What your statement "has to built against musl" means? Can I achieve that by using Ubuntu, Debian or Amazon Linux by installing the special packages? Or/And I need to change some configuration of a system or a project?

Thank you.

**Comment by davidbarsky** [comment] 2020-01-23 16:18
@konstantinvlasenko Sorry, that's my bad! Nothing to apologize for: I was curt in my previous message. You'll need to build against the `x86_64-unknown-linux-musl` target, which _statically_ links against the [musl-libc](https://www.musl-libc.org/). You _can_ install musl-libc on Ubuntu/Debian/Amazon Linux; some of the instructions on https://wiki.debian.org/musl#Installation cover that. You'll also need to add the `x86_64-unknown-linux-musl` target via Rustup: https://doc.rust-lang.org/edition-guide/rust-2018/platform-and-target-support/musl-support-for-fully-static-binaries.html.

All that being said, I am primarily a macOS user (with the occasional Amazon Linux usage), so I can't really tell you how to install Musl on a Debian-based system. Personally, I build everything via a Docker image.

**Comment by davidbarsky** [comment] 2020-01-23 16:18
(I also apologize if I over-explained anything to you!)

**Comment by konstantinvlasenko** [comment] 2020-01-23 19:28
Works! Works! Works!
@davidbarsky Thank you very much!

So in my case after following all the steps from here https://aws.amazon.com/blogs/opensource/rust-runtime-for-aws-lambda/ I was missing this one command in my Ubuntu instance:

> apt-get install musl

**Comment by chumaumenze** [comment] 2020-06-06 16:47
@davidbarsky I am currently facing this issue. I initially tried building with `musl` but the problem is that some crates rely heavily on C++ libraries. Static linking to the libraries definitely require some extra work (time) as described in https://github.com/rust-lang/rust/issues/36710#issuecomment-249634183.

Is there another way to resolve this?

**Comment by davidbarsky** [comment] 2020-06-06 17:18
@chumaumenze That makes sense. Trying to build crates with C/C++ dependencies isn't trivial. Unfortunately, there isn't anything that you can do at the moment. To properly resolve this issue, the runtime environment needs to be updated to use Amazon Linux 2, which has a significantly more recent glibc. I'm unable to share a date for when that work will be completed, but I'll let you know when that update has launched.

**Comment by rimutaka** [comment] 2020-06-16 23:39
@softprops , would it be better to replace 
> Since Lambda uses Amazon Linux, you'll need to target your executable for an `x86_64-linux` platform.

with 

> Since Lambda uses Amazon Linux, you'll need to target your executable for `x86_64-unknown-linux-musl` platform.

in the ReadMe (https://github.com/awslabs/aws-lambda-rust-runtime#aws-cli)?

I managed to get my Lambda going after targeting `-musl`.

**Comment by softprops** [comment] 2020-06-17 00:00
That doc is still true but when expanded, you've got options.


For local builds musl seems reliable with the tradeoff I'm warming up to of making sure your os or the one your building on has all of the musl prerequisites manually installed. This varies by os.

This is the approach I'm trying to get sam team to accept https://github.com/awslabs/aws-lambda-builders/pull/174 (available someday maybe)

And one I'm experimenting with in the serverless framework https://github.com/softprops/serverless-rust/blob/master/README.md#-experimental-local-builds (available today)

The alternative is to build on a container that matches the lambda runtime. The tradeoff here is that assumes docker. Docker is most likely already present on many dev envs but comes with some limitations of what is preinstalled in that docker image https://github.com/softprops/lambda-rust. (available today)

**Comment by brainstorm** [comment] 2020-06-18 00:38
I had to extend a cross container heavily to support a bioinformatics C library to support MUSL (and thus run on lambda):

https://github.com/rust-bio/rust-htslib/pull/193

Here's the docker result of the moves I had to go through to get all deps in order and compiled statically w/ MUSL on an extended Rust cross container:

https://github.com/rust-bio/rust-htslib/blob/master/docker/Dockerfile.musl

Works like a charm now, but I had to sweat this for a while :-S

**Comment by brainstorm** [comment] 2021-08-19 04:08
I'd actually close this issue and direct folks to `provided.al2`, all the MUSL tooling is not required anymore... unless there's an edge usecase I'm not aware of nowadays?

**Comment by coltonweaver** [comment] 2021-11-03 01:49
Hey, I've added references to provided.al2 in the README now. Closing this issue.

**Closed by coltonweaver** 2021-11-03 01:49 UTC
Labels: question
